# Generated by Django 4.1 on 2022-08-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_name',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
